### ISSUE TITLE
config.json will be overwritten by git pull

### ISSUE THREAD

**Issue by ctroller** [nittendev/LoopiaDynamicDNSClient#2]
If you make local modifications to your config.json file and then pull or reset the latest changes from the repo, your changes can/will be overwritten by the remote origin.

## Expected Behavior
config.json should remain untouched

## Current Behavior
config.json will become flagged for a merge / change

## Possible Solution
Provide a config.sample.json that will reflect repository config changes.

## Steps to Reproduce
1. Check out repo
2. Modify config.json
3. `git reset --hard`

**Comment by nittendev** [comment]
Issue addressed. Now including sample.config.json for demonstration only.
